/*!
 * Copyright (C) 2012-2013, The SwitchyOmega Authors. Please see the AUTHORS file
 * for details.
 *
 * This file is part of SwitchyOmega.
 *
 * SwitchyOmega is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SwitchyOmega is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SwitchyOmega.  If not, see <http://www.gnu.org/licenses/>.
 */

var strings = [
  "appNameShort",
  "condition_hostWildcard",
  "condition_hostRegex",
  "condition_hostLevels",
  "condition_urlWildcard",
  "condition_urlRegex",
  "condition_keyword",
  "condition_always",
  "condition_never",
  "dialog_close",
  "dialog_save",
  "dialog_ok",
  "dialog_cancel",
  "options_title",
  "options_navHeader_setting",
  "options_navHeader_profiles",
  "options_tab_ui",
  "options_tab_general",
  "options_tab_importExport",
  "options_newProfile",
  "options_group_miscOptions",
  "options_confirmDeletion",
  "options_refreshOnProfileChange",
  "options_group_switchOptions",
  "options_startupProfile",
  "options_quickSwitch",
  "options_cycledProfiles",
  "options_cycledProfilesHelp",
  "options_notCycledProfiles",
  "options_group_proxyChanges",
  "options_revertProxyChanges",
  "options_group_importExportProfile",
  "options_exportPacFile",
  "options_exportPacFileHelp",
  "options_group_importExportSettings",
  "options_makeBackup",
  "options_makeBackupHelp",
  "options_restoreLocal",
  "options_restoreLocalHelp",
  "options_restoreOnline",
  "options_restoreOnlinePlaceholder",
  "options_restoreOnlineSubmit",
  "options_profileTabPrefix",
  "options_renameProfile",
  "options_deleteProfile",
  "options_group_proxyServers",
  "options_proxy_scheme",
  "options_proxy_protocol",
  "options_proxy_server",
  "options_proxy_port",
  "options_scheme_default",
  "options_protocol_direct",
  "options_protocol_useDefault",
  "options_proxy_single",
  "options_group_bypassList",
  "options_bypassListHelp",
  "options_group_pacUrl",
  "options_group_pacScript",
  "options_pacUrlHelp",
  "options_group_ruleListResult",
  "options_ruleListMatchProfile",
  "options_ruleListDefaultProfile",
  "options_group_ruleListUrl",
  "options_ruleListUrlHelp",
  "options_group_ruleListText",
  "options_group_switchRules",
  "options_sort",
  "options_conditionType",
  "options_conditionDetails",
  "options_resultProfile",
  "options_conditionActions",
  "options_addCondition",
  "options_switchDefaultProfile",
  "options_hostLevelsBetween",
  "options_modalHeader_renameProfile",
  "options_modalHeader_deleteProfile",
  "options_deleteProfileConfirm",
  "options_modalHeader_cannotDeleteProfile",
  "options_profileReferredBy",
  "options_modifyReferringProfiles",
  "options_newProfileName",
  "options_profileNameEmpty",
  "options_profileNameConflict",
  "options_modalHeader_deleteRule",
  "options_deleteRuleConfirm",
  "options_deleteRule",
  "options_modalHeader_resetRules",
  "options_resetRulesConfirm",
  "options_resetRules",
  "options_modalHeader_newProfile",
  "options_profileType",
  "options_profileTypeFixedProfile",
  "options_profileDescFixedProfile",
  "options_profileTypePacProfile",
  "options_profileDescPacProfile",
  "options_profileTypeSwitchProfile",
  "options_profileDescSwitchProfile",
  "options_profileTypeSwitchyRuleListProfile",
  "options_profileDescSwitchyRuleListProfile",
  "options_profileTypeAutoProxyRuleListProfile",
  "options_profileDescAutoProxyRuleListProfile",
  "options_createProfile"
];
